/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  421614: {
    FactoryPrestaciones: {
      address: "0x09D6cB923bee3bF6907303EdF6364D940A5897FA",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "_nombreEmpresa",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "_idEmpresa",
              type: "string",
            },
          ],
          name: "CreacionEmpresa",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_nombreEmpresa",
              type: "string",
            },
            {
              internalType: "string",
              name: "_idEmpresa",
              type: "string",
            },
          ],
          name: "crearEmpresa",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "listaEmpresas",
          outputs: [
            {
              internalType: "contract Prestaciones",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
