/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    FactoryPrestaciones: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "_nombreEmpresa",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "_idEmpresa",
              type: "string",
            },
          ],
          name: "CreacionEmpresa",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_nombreEmpresa",
              type: "string",
            },
            {
              internalType: "string",
              name: "_idEmpresa",
              type: "string",
            },
          ],
          name: "crearEmpresa",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "listaEmpresas",
          outputs: [
            {
              internalType: "contract Prestaciones",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    Prestaciones: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "_nombreEmpresa",
              type: "string",
            },
            {
              internalType: "string",
              name: "_idEmpresa",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "trabajador",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "monto",
              type: "uint256",
            },
          ],
          name: "DepositoPrestaciones",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "trabajador",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum Prestaciones.EstadoSolicitud",
              name: "estado",
              type: "uint8",
            },
          ],
          name: "RespuestaSolicitud",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "trabajador",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum Prestaciones.RetiroSolicitud",
              name: "tipo",
              type: "uint8",
            },
          ],
          name: "RetiroSolicitado",
          type: "event",
        },
        {
          inputs: [],
          name: "PORCENTAJE_MAXIMO_RETIRO",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "aave",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trabajador",
              type: "address",
            },
          ],
          name: "aceptarSolicitud",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "arbitraje",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "asset",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_aave",
              type: "address",
            },
            {
              internalType: "address",
              name: "_asset",
              type: "address",
            },
          ],
          name: "configurarStakProtocol",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trabajador",
              type: "address",
            },
          ],
          name: "consultarBalanceAave",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trabajador",
              type: "address",
            },
          ],
          name: "consultarIntereses",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trabajador",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_monto",
              type: "uint256",
            },
          ],
          name: "depositarPrestaciones",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "empresa",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trabajador",
              type: "address",
            },
          ],
          name: "finalizarContratacion",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "idEmpresa",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "listaTrabajadores",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "nombreEmpresa",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "obtenerTrabajadores",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trabajador",
              type: "address",
            },
          ],
          name: "rechazarSolicitud",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trabajador",
              type: "address",
            },
            {
              internalType: "string",
              name: "_cedula",
              type: "string",
            },
            {
              internalType: "string",
              name: "_nombre",
              type: "string",
            },
          ],
          name: "registrarTrabajador",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum Prestaciones.RetiroSolicitud",
              name: "_tipoRetiro",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "_porcentaje",
              type: "uint8",
            },
          ],
          name: "solicitarRetiro",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "solicitudesRetiro",
          outputs: [
            {
              internalType: "enum Prestaciones.RetiroSolicitud",
              name: "tipo",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "porcentaje",
              type: "uint8",
            },
            {
              internalType: "enum Prestaciones.EstadoSolicitud",
              name: "estado",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "fechaSolicitud",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "trabajadores",
          outputs: [
            {
              internalType: "string",
              name: "cedula",
              type: "string",
            },
            {
              internalType: "string",
              name: "nombre",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "saldo",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "porcentajeRetirado",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "ultimaFechaDeposito",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "estatus",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
